### PR TITLE
Update to Freedesktop 20.08 + build on aarch64

### PR DESCRIPTION
**Pull request by hfiguiere**
- [ ] Test on Raspberry Pi
- [x] Test on plain x86_64 since the SDK got updated.

### CODE REVIEW

**Comment by mki1967** [comment]
Hi @hfiguiere, have you managed to run it on something other than   x86_64 ? (I do not have access to to Linuxes on other architectures and I have not expected  programs using https://github.com/go-gl/gl to work there.)

**Comment by hfiguiere** [comment]
It's a bummer. As is, it fails with GLX on a Raspberry Pi 400.

I'll investigate more.

**Comment by hfiguiere** [comment]
> Hi @hfiguiere, have you managed to run it on something other than x86_64 ? (I do not have access to to Linuxes on other architectures and I have not expected programs using https://github.com/go-gl/gl to work there.)

I'm sure there is something that can be done (see above comment).

(FreeCAD can run on that system, at least with the debian packages)

**Comment by mki1967** [comment]
In this case I feel totally dependent on whether https://github.com/go-gl supports the architecture.

**Comment by hfiguiere** [comment]
It's not an architecture problem. It's a GL programing problem.

**Pull request closed without merging**
